# This workflow will run tests using node and then publish a package to NPM when a release is created
# Also deploy to GitHub pages

name: Node.js Package

on:
    push:
        branches:
            - main
        paths-ignore:
            - '**.md'

jobs:
    build:
        timeout-minutes: 8
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            # - name: sonarQube scancode
            #   uses: sonarsource/sonarqube-scan-action@master
            #   env:
            #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            #       SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
            # - uses: sonarsource/sonarqube-quality-gate-action@master
            #  timeout-minutes: 5
            #  env:
            #      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - run: npm install
            # - run: npm test

    publish:
        name: Publish package to npmjs
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 18
                  registry-url: 'https://registry.npmjs.org'
            - run: git config --global user.email "ross@bsoltec.com"
            - run: git config --global user.name "Ross Chiu"
            - run: npm ci
            - run: npm version patch
            - run: npm run build
            - run: npm publish . && git push --tags && git push && echo \"Successfully released version $npm_package_version!\"
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

    deploy:
        name: Deploy site to gh-pages
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '18'
            - run: git config --global user.email "ross@bsoltec.com"
            - run: git config --global user.name "Ross Chiu"
            - run: npm install
            - run: npm run build-storybook
            - run: |
                  git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
                  npm run deploy -u "github-actions-bot <support+actions@github.com>"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
